### ISSUE TITLE
N2O in 3.A in IPCC2006_PRIMAP

### ISSUE THREAD

**Issue by rgieseke** [pik-primap/climate_categories#87]
Is N2O missing in the gases section here?

https://github.com/pik-primap/climate_categories/blob/12608f848be3f8bc18ed373552bb11dfac1d92e4/climate_categories/data/IPCC2006_PRIMAP.yaml#L3199

```yaml
3.A:
    title: Livestock
    comment: Methane emissions from enteric fermentation, and methane and nitrous
      oxide emissions from manure management.
    alternative_codes:
    - 3A
    info:
      gases:
      - CH4
      corresponding_categories_IPCC1996:
      - '4'
    children:
    - - 3.A.1
      - 3.A.2
 ```
N2O is included in subcategory 3.A.2:

https://github.com/pik-primap/climate_categories/blob/12608f848be3f8bc18ed373552bb11dfac1d92e4/climate_categories/data/IPCC2006_PRIMAP.yaml#L3363

```yaml
3.A.2:
    title: Manure Management
    comment: Methane and nitrous oxide emissions from the decomposition of manure
      under low oxygen or anaerobic conditions. These conditions often occur when
      large numbers of animals are managed in a confined area (e.g. dairy farms, beef
      feedlots, and swine and poultry farms), where manure is typically stored in
      large piles or disposed of in lagoons and other types of manure management systems.
    alternative_codes:
    - 3A2
    info:
      gases:
      - CH4
      - N2O
      ```
